camunda/element-templates-json-schema

- resources/schema.json
- test/fixtures/choices-missing-name.js
- test/fixtures/choices-missing-value.js
- test/fixtures/invalid-binding-type.js
- test/fixtures/invalid-camunda-in-business-key-type.js
- test/fixtures/invalid-camunda-in-type.js
- test/fixtures/invalid-camunda-out-type.js
- test/fixtures/invalid-camunda-out.js
- test/fixtures/invalid-camunda-property-type.js
- test/fixtures/invalid-execution-listener-type.js
- test/fixtures/invalid-field-type.js
- test/fixtures/invalid-input-parameter-type.js
- test/fixtures/invalid-output-parameter-type.js
- test/fixtures/invalid-property-type.js
- test/fixtures/missing-binding-name.js
- test/fixtures/missing-binding-source.js
- test/fixtures/missing-binding-variables-target.js
- test/fixtures/missing-binding.js
- test/fixtures/missing-choices.js
- test/fixtures/multiple-errors.js
- test/fixtures/number-value.js
- test/fixtures/scope-connector-missing-binding.js
- test/fixtures/scope-connector.js
- test/fixtures/scope-invalid.js
- test/spec/validationSpec.js
* Moves `properties` schema to own definition, to make it reusable for scopes
* Add schema for `scopes`
valid
```js
'scopes': {
'camunda:Connector': {
'properties': [
{
'label': 'ConnectorId',
'type': 'String',
'value': 'My Connector HTTP - GET'      
}
]
}
}
```
invalid
```js
'scopes': {
'foo': {
'properties': []
}
}
```
Closes #14
> Scopes Support

- package.json
- resources/schema.json
- test/fixtures/error-task-multiple.js
- test/fixtures/error-task.js
- test/fixtures/invalid-binding-type.js
- test/fixtures/invalid-camunda-error-event-definition-type.js
- test/fixtures/missing-binding-errorRef.js
- test/fixtures/scope-connector-legacy.js
- test/fixtures/scope-connector-missing-binding-legacy.js
- test/fixtures/scope-invalid-legacy.js
- test/fixtures/scope-invalid-type.js
- test/fixtures/scope-missing-binding.js
- test/fixtures/scope-missing-error-id.js
- test/fixtures/scope-missing-properties.js
- test/fixtures/scope-missing-type.js
- test/fixtures/scopes-multiple.js
- test/spec/validationSpec.js
Closes #20
* handle array scopes
* allow error event definitions
* validate for missing errorRef
* validate for property type ("String", "Hidden", "Dropdown")
* allow error scopes
* validate for missing id
> Array Scopes, Error Event Definitions & Scoped Error Bindings

- resources/schema.json
- test/fixtures/complex.js
- test/fixtures/constraints.js
- test/fixtures/entries-visible-boolean.js
- test/fixtures/invalid-applies-to.js
- test/fixtures/invalid-binding-type.js
- test/fixtures/invalid-constraints.js
- test/fixtures/invalid-multiple-mail-tasks.js
- test/fixtures/invalid-version.js
- test/fixtures/missing-binding.js
- test/fixtures/missing-properties.js
- test/fixtures/missing-template-id.js
- test/fixtures/missing-template-name.js
- test/fixtures/pattern-string.js
- test/fixtures/rpa-templates.js
- test/fixtures/scope-connector-missing-binding-legacy.js
- test/fixtures/scope-invalid-legacy.js
- test/fixtures/scope-missing-binding.js
- test/fixtures/scope-missing-error-id.js
- test/fixtures/scope-missing-properties.js
- test/fixtures/scope-missing-type.js
- test/spec/validationSpec.js
Fix smaller Schema issues while working on camunda/camunda-modeler#2159, especially to align with the existing Properties Panel behavior. That includes
* correct data types for `constraints.{minLength | maxLength}` properties (cf. #24)
* adjust error message for invalid binding type (cf. #25)
* adjust error messages for required properties
* adjust error message for legacy scope type
* adjust error message for `appliesTo` pattern
* fix a test case for template versions
* add additional allowed data types for `entriesVisible` & `property.constraints.pattern`
* add more complex test cases
----
Related to camunda/camunda-modeler#2159
Closes #24 
Closes #25
> Schema Adjustments + Cleanups

- test/spec/validationSpec.js
This ensures we initialize the validator only once for our tests suite. Otherwise, it would compile the schema _every single time_. The schema itself does not change, so there is no need to do this extra.
Also, compare the execution tests for single tests
**Before**
**After**
> test: initialize validator only once

- packages/element-templates-json-schema-shared/src/defs/base-properties.json
- packages/element-templates-json-schema-shared/src/defs/base.json
- packages/element-templates-json-schema-shared/src/defs/examples.json
- packages/element-templates-json-schema-shared/src/defs/groups.json
- packages/element-templates-json-schema/resources/schema.json
- packages/element-templates-json-schema/src/defs/examples.json
- packages/element-templates-json-schema/src/defs/properties.json
- packages/element-templates-json-schema/src/defs/scopes.json
- packages/element-templates-json-schema/src/schema.json
- packages/zeebe-element-templates-json-schema/resources/schema.json
- packages/zeebe-element-templates-json-schema/src/defs/examples.json
- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/src/schema.json
This provides better programming editor support by
* cleaning up descriptions
* removing unnecessary titles
* add examples
* add default values were examples are not applicable
Context: [Annotations docs](http://json-schema.org/understanding-json-schema/reference/generic.html#id2)
> Provide better editor annotations

- packages/element-templates-json-schema-shared/src/defs/base-properties.json
- packages/element-templates-json-schema/resources/schema.json
- packages/zeebe-element-templates-json-schema/resources/schema.json
- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/test/fixtures/feel-type-mismatch.js
- packages/zeebe-element-templates-json-schema/test/fixtures/feel.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/606
> feat: add `feel` property

- packages/element-templates-json-schema-shared/src/defs/base.json
- packages/element-templates-json-schema-shared/src/defs/examples.json
- packages/element-templates-json-schema/resources/schema.json
- packages/element-templates-json-schema/test/fixtures/element-type-invalid.js
- packages/element-templates-json-schema/test/fixtures/element-type.js
- packages/element-templates-json-schema/test/fixtures/invalid-applies-to.js
- packages/element-templates-json-schema/test/spec/validationSpec.js
- packages/zeebe-element-templates-json-schema/resources/schema.json
- packages/zeebe-element-templates-json-schema/test/fixtures/element-type-invalid.js
- packages/zeebe-element-templates-json-schema/test/fixtures/element-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-applies-to.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/572
AFAIK there are certain thinks we can't verify in the schema, like
- there can only be one `type` property
- the property value has to be part of `appliesTo`
Therefore, we just validate that
- it is of type `hidden`
- has a value that is of type `bpmn:someTask` (same validation we have for `appliesTo`)
The other options have to be checked during runtime.
> feat: add `type` binding

- packages/element-templates-json-schema-shared/src/defs/base.json
- packages/element-templates-json-schema/resources/schema.json
- packages/element-templates-json-schema/test/fixtures/element-type-no-value.js
- packages/element-templates-json-schema/test/spec/validationSpec.js
- packages/zeebe-element-templates-json-schema/resources/schema.json
- packages/zeebe-element-templates-json-schema/test/fixtures/element-type-no-value.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
related to https://github.com/bpmn-io/bpmn-js-properties-panel/pull/648#discussion_r839540764
This PR ensures that a template with `elementType` but no value is invalid
> fix: required `value` for element type property

- packages/element-templates-json-schema-shared/src/defs/base-properties.json
- packages/element-templates-json-schema-shared/src/defs/condition.json
- packages/element-templates-json-schema-shared/src/defs/examples.json
- packages/element-templates-json-schema/resources/schema.json
- packages/element-templates-json-schema/test/fixtures/condition-default-type.js
- packages/element-templates-json-schema/test/fixtures/condition-missing-condition-keyword.js
- packages/element-templates-json-schema/test/fixtures/condition-missing-property.js
- packages/element-templates-json-schema/test/fixtures/condition-wrong-type.js
- packages/element-templates-json-schema/test/fixtures/condition-wrong-types.js
- packages/element-templates-json-schema/test/fixtures/condition.js
- packages/element-templates-json-schema/test/spec/validationSpec.js
- packages/zeebe-element-templates-json-schema/resources/schema.json
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-default-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-missing-condition-keyword.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-missing-property.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-wrong-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-wrong-types.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
```json
"condition": {
"examples": [
{
"type": "simple",
"property": "httpMethod",
"equals": "GET"
},
{
"type": "simple",
"property": "httpMethod",
"oneOf": [ "POST", "PUT", "DELETE" ]
}
]
}
```
Closes #54
> Support property condition: `simple`

- README.md
- package.json
Adds an `npm run release:alpha` script to publish alpha releases.
Context: https://camunda.slack.com/archives/GP70M0J6M/p1653920841326989
Context: https://github.com/lerna/lerna/blob/main/commands/publish/README.md#--dist-tag-tag
> chore: add alpha release task

- packages/zeebe-element-templates-json-schema/resources/error-messages.json
- packages/zeebe-element-templates-json-schema/resources/schema.json
- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/src/error-messages.json
- packages/zeebe-element-templates-json-schema/test/fixtures/language.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
Allows users to pass a `language` meta-data with `Text` elements:
```json
{
"name": "My special Template
...
"properties: [
{
"label": "Query/Mutation",
"type": "Text",
"language": "graphql",
"binding": {
"type": "zeebe:input",
"name": "graphql.query"
}
}
],
...
}
```
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/858
> feat: support `language` on `Text` elements

- packages/zeebe-element-templates-json-schema/resources/schema.json
- packages/zeebe-element-templates-json-schema/src/defs/examples.json
- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/test/fixtures/cloud-rest-connector.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-binding-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-task-definition-retries-type.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
For https://github.com/camunda/camunda-modeler/issues/2936, start by defining `zeebe:taskDefinition:retries` in the schema.
@nikku you probably have a lot to say about this. I mostly duplicated behaviour of `zeebe:taskDefinition:type`. There is no special type (its value should be limited to positive integer) but I had no idea how to do that.
> feat: support zeebe:taskDefinition:retries

- lerna.json
- package-lock.json
- package.json
Follow up from https://github.com/camunda/element-templates-json-schema/pull/99
Lerna v7 removes package management commands and leaves it up to the package manager aka `npm`
removing `lerna bootstrap`:
> Replace lerna bootstrap with npm install (or yarn/pnpm). If you are already performing your package manager's install command somewhere in your workflow before where you had previously called lerna bootstrap, then you can just delete it instead.
> If you were just using lerna bootstrap without any advanced hoisting concerns, feel free to choose from any of the package managers, they all offer robust workspaces implementations.
removing `useWorkspaces`:
> We now use your package manager's workspaces configuration by default
I believe this is all we need to do but please have a look and …
> deps: update to `lerna@7.0.0`

- packages/zeebe-element-templates-json-schema/src/defs/element-type.json
- packages/zeebe-element-templates-json-schema/src/defs/template.json
- packages/zeebe-element-templates-json-schema/test/fixtures/message-property-invalid-event-definition.js
- packages/zeebe-element-templates-json-schema/test/fixtures/message-property-valid.js
- packages/zeebe-element-templates-json-schema/test/fixtures/message-subscription-property-invalid-event-definition.js
- packages/zeebe-element-templates-json-schema/test/fixtures/message-subscription-property-valid.js
Related to https://github.com/camunda/camunda-modeler/issues/3573
> feat: support receive and send task templating

- packages/element-templates-json-schema-shared/src/defs/condition.json
- packages/element-templates-json-schema/test/fixtures/condition-default-type.js
- packages/element-templates-json-schema/test/fixtures/condition-missing-condition-keyword.js
- packages/element-templates-json-schema/test/fixtures/condition-wrong-types.js
- packages/element-templates-json-schema/test/fixtures/condition.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-default-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-empty-allMatch.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-missing-condition-keyword.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-wrong-types.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition.js
related to https://github.com/bpmn-io/bpmn-js-element-templates/issues/19
> feat(condition): add `isVisible` condition

- packages/element-templates-json-schema-shared/src/base-error-messages.json
- packages/element-templates-json-schema-shared/src/defs/base-properties.json
- packages/element-templates-json-schema-shared/src/defs/condition.json
- packages/element-templates-json-schema-shared/test/helpers/index.js
- packages/element-templates-json-schema/test/fixtures/condition-default-type.js
- packages/element-templates-json-schema/test/fixtures/condition-missing-condition-keyword.js
- packages/element-templates-json-schema/test/fixtures/condition-missing-property.js
- packages/element-templates-json-schema/test/fixtures/condition-wrong-type.js
- packages/element-templates-json-schema/test/fixtures/condition-wrong-types.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-default-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-empty-allMatch.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-missing-condition-keyword.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-missing-property.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-on-itself-allMatch.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-on-itself-dropdown-choices.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-on-itself.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-wrong-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-wrong-types.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
Closes #125
---
Note that this requires the validator to accept `$data` property. The monaco editor handles this correctly, and in `ajv` you need to pass `$data: true` to the constructor.
> feat: disallow condition depending on the containing property

- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/src/error-messages.json
- packages/zeebe-element-templates-json-schema/test/fixtures/feel-type-mismatch.js
- packages/zeebe-element-templates-json-schema/test/fixtures/feel.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-property-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-input-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-output-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-property-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-task-definition-type-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-task-definition.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-task-header-type.js
- adds `staticValue` option for feel, only valid on Number and Boolean
related to https://github.com/camunda/camunda-modeler/issues/3622
> feat(zeebe): allow number and boolean everywhere

- packages/element-templates-json-schema-shared/src/defs/condition.json
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-allMatch-one-condition.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-on-itself-allMatch.js
- packages/zeebe-element-templates-json-schema/test/fixtures/condition-on-itself-dropdown-choices.js
This removes the safeguard for depending on itself for the conditions from the title but keeps it for a simple condition. The PR includes @marstamm 's test cases from https://github.com/camunda/element-templates-json-schema/pull/135
Closes #133
> Fix `allOf` and `choices`

- packages/element-templates-json-schema-shared/src/defs/base-properties.json
- packages/element-templates-json-schema/test/fixtures/number-value.js
- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/test/fixtures/feel-value-mismatch.js
- packages/zeebe-element-templates-json-schema/test/fixtures/number-value.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
closes https://github.com/camunda/element-templates-json-schema/issues/138
related to https://github.com/bpmn-io/bpmn-js-element-templates/pull/73#issuecomment-1970834323
Note: as opposed to the proposed solution in https://github.com/bpmn-io/bpmn-js-element-templates/pull/73#issuecomment-1970834323, I did not add pattern validation. This would be a breaking change and could break already existing, currently working templates.
We can add pattern validation in a follow-up, but I do not want to push it in the current release.
> fix: validate type of `value`

- packages/element-templates-json-schema-shared/CHANGELOG.md
- packages/element-templates-json-schema-shared/src/defs/base-properties.json
- packages/element-templates-json-schema/test/fixtures/placeholder-invalid-property.js
- packages/element-templates-json-schema/test/fixtures/placeholder-invalid-type.js
- packages/element-templates-json-schema/test/fixtures/placeholder.js
- packages/element-templates-json-schema/test/spec/validationSpec.js
- packages/zeebe-element-templates-json-schema/CHANGELOG.md
- packages/zeebe-element-templates-json-schema/test/fixtures/placeholder-invalid-property.js
- packages/zeebe-element-templates-json-schema/test/fixtures/placeholder-invalid-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/placeholder.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
This PR add support for `placeholder` property on `String` and `Text` fields.
Related to https://github.com/bpmn-io/bpmn-js-element-templates/issues/92
> feat: support `placeholder` property

- packages/zeebe-element-templates-json-schema/src/defs/engines.json
- packages/zeebe-element-templates-json-schema/src/schema.json
- packages/zeebe-element-templates-json-schema/test/fixtures/engines-invalid-version.js
- packages/zeebe-element-templates-json-schema/test/fixtures/engines-invalid.js
- packages/zeebe-element-templates-json-schema/test/fixtures/engines-no-camunda.js
- packages/zeebe-element-templates-json-schema/test/fixtures/engines.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
Closes https://github.com/camunda/element-templates-json-schema/issues/146
Add `engines` property to include a list of platforms and their versions compatible with element template.
> feat: support engines property

- packages/zeebe-element-templates-json-schema/CHANGELOG.md
- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/src/error-messages.json
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-binding-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/linked-resource-invalid-property.js
- packages/zeebe-element-templates-json-schema/test/fixtures/linked-resource-missing-linkName.js
- packages/zeebe-element-templates-json-schema/test/fixtures/linked-resource.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
This PR adds schema support for `linkedResource` templating.
Related to https://github.com/bpmn-io/bpmn-js-element-templates/issues/137
> feat(zeebe): add zeebe:LinkedResource

- package-lock.json
- package.json
- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-input-feel.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-input-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-output-feel.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-output-type.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
Adds a new condition that requires `Boolean` and `Number` properties with binding `zeebe:input` or `zeebe:output` to be `"feel": "static"`. This is to ensure their values will be persisted as FEEL expressions and not intepreted as strings.
```json
{
"label": "Foo",
"type": "Boolean",
"binding": {
"type": "zeebe:input",
"name": "foo"
}
}
```
would result in
```xml
<zeebe:input source="true" target="foo" />
```
and is therefore interpreted as string.
```json
{
"label": "Foo",
"type": "Boolean",
"binding": {
"type": "zeebe:input",
"name": "foo"
},
"feel": "static"
}
```
results in
```xml
<zeebe:input source="=true" target="foo" />
```
and is therefore interpreted as boolean.
> Require `Boolean` and `Number` properties with binding `zeebe:input` or `zeebe:output` to be `"feel": "static"`

- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-input-feel.js
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-zeebe-output-feel.js
Following up on https://github.com/camunda/element-templates-json-schema/pull/154 this pull request changes the schema to allow both `static` and `optional` for `Boolean` and `Number` properties with a `zeebe:input` or `zeebe:output` binding as these are valid use cases and both `static` and `optional` [will result in a FEEL expression](https://github.com/bpmn-io/bpmn-js-element-templates/blob/main/src/cloud-element-templates/util/FeelUtil.js#L2C36-L2C57).
So both of these are valid:
```json
{
"label": "Optional FEEL Boolean",
"type": "Boolean",
"binding": {
"type": "zeebe:input",
"name": "foo"
},
"feel": "optional"
},
{
"label": "Static FEEL Boolean",
"type": "Boolean",
"binding": {
"type": "zeebe:input",
"name": "foo"
},
"feel": "static"
},
```
In the properties panel this will look …
> fix(zeebe): require `"feel":"optional/static"` for `Boolean/Number` I/O

- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/src/defs/template.json
- packages/zeebe-element-templates-json-schema/src/error-messages.json
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-binding-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/zeebe-user-task-invalid.js
- packages/zeebe-element-templates-json-schema/test/fixtures/zeebe-user-task.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
Support `zeebe:userTask` binding property. If specified, it ensures that a (user) task has Camunda user task set as the implementation type.
Related to https://github.com/camunda/camunda-modeler/issues/4582
To ensure you provided everything we need to look at your PR:
> feat: support `zeebe:userTask` binding property

- packages/element-templates-json-schema-shared/test/helpers/index.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
Allows developers to directly copy the error to the fixture file. 
I don't mind if this is rejected, it feels a little "odd" but it sped up my workflow immensely so far. Maybe there is a better way to get the full validation error for the fixture file, which I am unaware of. 
Discussion started [here](https://github.com/camunda/element-templates-json-schema/pull/169#discussion_r2144468155).
The output for failing tests now looks like this: 
```
1) validation
should validate single template
zeebe:calledDecision
called-decision-incorrect-property:
AssertionError: Errors from validation do not match expected.
Validation returned this error:
[
{
keyword: "errorMessage",
dataPath: "/properties/0/binding/property",
schemaPath: "#/allOf/1/allOf/5/then/allOf/0/properties/properties/contains/proper …
```
> test: add full validation error output for failed test

- packages/zeebe-element-templates-json-schema/src/defs/template.json
- packages/zeebe-element-templates-json-schema/test/fixtures/business-rule-task-conflicting-bindings.js
- packages/zeebe-element-templates-json-schema/test/fixtures/business-rule-task-conflicting-deprecated-bindings.js
- packages/zeebe-element-templates-json-schema/test/fixtures/feel-missing-type-multiple-templates.js
- packages/zeebe-element-templates-json-schema/test/fixtures/feel-missing-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/script-task-conflicting-bindings.js
- packages/zeebe-element-templates-json-schema/test/fixtures/script-task-conflicting-deprecated-bindings.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
I made the "not" clauses less broadly applicable. However, i am still not sure what casuses the "then"clause to be evaluated in the first place as the properties array never contains an element with binding type `calledDecision` or `script`. 
Presumably, it's somehow not strict enough when evaluating an array of element templates, but I am a bit at a loss why. 
Related to https://github.com/camunda/element-templates-json-schema/pull/176#issuecomment-3019586270
To ensure you provided everything we need to look at your PR:
> fix: don't complain about incorrect binding type

- packages/zeebe-element-templates-json-schema/src/defs/properties.json
- packages/zeebe-element-templates-json-schema/src/defs/properties/binding/taskSchedule.json
- packages/zeebe-element-templates-json-schema/src/defs/properties/taskSchedule.json
- packages/zeebe-element-templates-json-schema/src/defs/template.json
- packages/zeebe-element-templates-json-schema/src/error-messages.json
- packages/zeebe-element-templates-json-schema/test/fixtures/invalid-binding-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/task-schedule/invalid-element-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/task-schedule/invalid-input-type.js
- packages/zeebe-element-templates-json-schema/test/fixtures/task-schedule/invalid-iso-date-value.js
- packages/zeebe-element-templates-json-schema/test/fixtures/task-schedule/invalid-property.js
- packages/zeebe-element-templates-json-schema/test/fixtures/task-schedule/invalid-value.js
- packages/zeebe-element-templates-json-schema/test/fixtures/task-schedule/missing-property.js
- packages/zeebe-element-templates-json-schema/test/fixtures/task-schedule/missing-zeebe-user-task.js
- packages/zeebe-element-templates-json-schema/test/fixtures/task-schedule/valid-feel.js
- packages/zeebe-element-templates-json-schema/test/fixtures/task-schedule/valid.js
- packages/zeebe-element-templates-json-schema/test/spec/validationSpec.js
- Element `zeebe:taskSchedule` can be templated
- Property `zeebe:taskSchedule#dueDate` can be templated
- Property `zeebe:taskSchedule#followUpDate` can be templated
- Both properties are String/Text typed with FEEL support or a Dropdown or Hidden. 
- the `value` set in the template for these properties can only be ISO 8601 date time
- `zeebe:taskSchedule` can only be set if `zeebe:UserTask` is set. 
- `zeebe:taskSchedule` can only exist in a `bpmn:UserTask`
- At least one of the properties needs to be set. 
related to https://github.com/camunda/camunda-modeler/issues/5093
To ensure you provided everything we need to look at your PR:
> feat: add zeebe:taskSchedule
